// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbjUzJyVwdgs7kjp0_ZWi7FuHhMtsr2kY',
    appId: '1:250452260600:web:54df960425d959b1ceed0d',
    messagingSenderId: '250452260600',
    projectId: 'gid-todo-flutter-app',
    authDomain: 'gid-todo-flutter-app.firebaseapp.com',
    storageBucket: 'gid-todo-flutter-app.appspot.com',
    measurementId: 'G-W032CY2M2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn1voGy5k7eFWkNZlFv_pbFaCbcbU_t6k',
    appId: '1:250452260600:android:668827206df7c69cceed0d',
    messagingSenderId: '250452260600',
    projectId: 'gid-todo-flutter-app',
    storageBucket: 'gid-todo-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiDPwzKwvaqLyBcQOmdHlrcepkl3cCvYA',
    appId: '1:250452260600:ios:8e267033d9758c90ceed0d',
    messagingSenderId: '250452260600',
    projectId: 'gid-todo-flutter-app',
    storageBucket: 'gid-todo-flutter-app.appspot.com',
    iosClientId: '250452260600-nfmdb7sv9kjigg9hr28ds1jd1ha6gdhm.apps.googleusercontent.com',
    iosBundleId: 'com.aflion.gid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiDPwzKwvaqLyBcQOmdHlrcepkl3cCvYA',
    appId: '1:250452260600:ios:8e267033d9758c90ceed0d',
    messagingSenderId: '250452260600',
    projectId: 'gid-todo-flutter-app',
    storageBucket: 'gid-todo-flutter-app.appspot.com',
    iosClientId: '250452260600-nfmdb7sv9kjigg9hr28ds1jd1ha6gdhm.apps.googleusercontent.com',
    iosBundleId: 'com.aflion.gid',
  );
}
